---

- name: primeiro exercicio
  hosts: all
  vars:
    - usuario: null

  tasks:
    - name: criando usuarios devops, developer e "{{usuario}}"
      user:
        name: "{{item}}"
        state: present
      with_items:
        - "{{usuario}}"
        - devops
        - developer

    - name: instalando pacotes
      package:
        name:
          - htop
          - vim
          - cowsay
          - figlet

    - name: copiando arquivo devops
      file:
        path: /tmp/devops
        state: touch

    - name: colocando conteudo
      blockinfile:
        path: /tmp/devops
        block: |
          sou devops
          na 4linux

    - name: copiando arquivo index
      file:
        path: /tmp/index
        state: touch
      when: ansible_hostname == "devops"


    - name: colocando conteudo
      blockinfile:
        path: /tmp/index
        block: |
          sou devops
      when: ansible_hostname == "devops"

