---
- name: Instalando Jenkins
  hosts: automation
  tasks:
    - name: intalando wget
      package:
        name: wget

    - name: adicionando o repositorio
      shell: "wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo"

    - name: adicionando a chave do repo
      shell: "rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key"

    - name: instalando jenkins
      package:
        name: jenkins 
